[project]
name = "retakid-backend"
version = "0.1.0"
description = "Backend ML and Data Pipeline for Retak.id"
requires-python = ">=3.10, <3.13"
dependencies = [
    "tensorflow>=2.15.0",
    "tensorflow-hub",
    "numpy",
    "pandas",
    "matplotlib",
    "selenium",
    "beautifulsoup4",
    "requests",
    "pillow",
    "scikit-learn",
    "duckduckgo_search",
    "imagehash",
    "opencv-python",
    "pyyaml",
    "dvc>=3.67.1",
    "ddgs",
    "fake-useragent",
    "mlflow",
]

[tool.uv]
dev-dependencies = [
    "ipykernel",
    "black",
    "pytest",
]
